// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPVjFgg9lS9YgJavJzTrYXILxUg1QJEnQ',
    appId: '1:324763105742:web:8510cf98dd40ca1c65539f',
    messagingSenderId: '324763105742',
    projectId: 'mydaymate-391c2',
    authDomain: 'mydaymate-391c2.firebaseapp.com',
    storageBucket: 'mydaymate-391c2.firebasestorage.app',
    measurementId: 'G-V45HFX09W4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB79kbldLbvqklxi9g5OQf4qWb5jR_omDQ',
    appId: '1:324763105742:android:b2bfc5d72420514665539f',
    messagingSenderId: '324763105742',
    projectId: 'mydaymate-391c2',
    storageBucket: 'mydaymate-391c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4hWlFZJgru-rzoQHNQObA0Q3ZXPhoTvQ',
    appId: '1:324763105742:ios:8e7cb9226957fc1065539f',
    messagingSenderId: '324763105742',
    projectId: 'mydaymate-391c2',
    storageBucket: 'mydaymate-391c2.firebasestorage.app',
    iosBundleId: 'com.example.mydaymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4hWlFZJgru-rzoQHNQObA0Q3ZXPhoTvQ',
    appId: '1:324763105742:ios:8e7cb9226957fc1065539f',
    messagingSenderId: '324763105742',
    projectId: 'mydaymate-391c2',
    storageBucket: 'mydaymate-391c2.firebasestorage.app',
    iosBundleId: 'com.example.mydaymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPVjFgg9lS9YgJavJzTrYXILxUg1QJEnQ',
    appId: '1:324763105742:web:8cea011d7c205af065539f',
    messagingSenderId: '324763105742',
    projectId: 'mydaymate-391c2',
    authDomain: 'mydaymate-391c2.firebaseapp.com',
    storageBucket: 'mydaymate-391c2.firebasestorage.app',
    measurementId: 'G-809ZK9S65N',
  );
}
